version: "3.8"

services:
  db:
    image: postgres:15
    container_name: encryptovault_db
    restart: always
    environment:
      POSTGRES_USER: encrypto_user
      POSTGRES_PASSWORD: encrypto_password
      POSTGRES_DB: encryptovault
    ports:
      - "5432:5432"
    volumes:
      - encryptovault_db_data:/var/lib/postgresql/data

volumes:
  encryptovault_db_data:
